version: '2'
services:

  # a sample app with metrics enabled
  app:
    build: './api'
    restart: always
    ports:
      - 5000:5000
   

  # the Prometheus server
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  # Grafana for visualization
  grafana:
    image:  grafana/grafana
    depends_on:
      - prometheus
    volumes:
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards

    ports:
      - '3000:3000'
