global:
  scrape_interval: 3s
  evaluation_interval: 15s

  external_labels:
      monitor: 'example-app'


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'flask-app-setup'
    dns_sd_configs:
      - names: ['app']
        port: 5000
        type: A
        refresh_interval: 5s